# Generated by Django 3.0.7 on 2020-07-24 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=50, verbose_name='アイテム')),
                ('quantity', models.IntegerField(default=1, verbose_name='数量')),
                ('unit_price', models.CharField(max_length=20, verbose_name='単価')),
                ('amount_money', models.CharField(max_length=20, verbose_name='金額')),
            ],
            options={
                'verbose_name': 'アイテム',
                'verbose_name_plural': 'アイテム',
            },
        ),
    ]
